# -*- coding: utf-8 -*-
"""blip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QKvNwH_e3zYKIPFCWVI24mfHxJCbw1Z
"""

!pip install -q transformers timm accelerate sentencepiece

from transformers import BlipProcessor, BlipForQuestionAnswering
from PIL import Image
from google.colab import files
import torch

# 3. Load Model and Processor
print("Loading BLIP VQA Model...")

processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-vqa-base"
)

model = BlipForQuestionAnswering.from_pretrained(
    "Salesforce/blip-vqa-base"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

print("Model loaded successfully on", device)

print("\nUpload an image:")
uploaded = files.upload()

image_path = list(uploaded.keys())[0]
image = Image.open(image_path).convert("RGB")

display(image)

print("\nImage uploaded successfully.")
print("You can now ask multiple questions about the image.")
print("Type 'exit', 'quit', or 'no' to stop.\n")

while True:

    question = input("Enter your question: ")

    if question.lower() in ["exit", "quit", "no"]:
        print("\nSession Ended. Thank you!")
        break

    inputs = processor(
        image,
        question,
        return_tensors="pt"
    ).to(device)

    outputs = model.generate(**inputs)

    answer = processor.decode(
        outputs[0],
        skip_special_tokens=True
    )

    print("\nAnswer :", answer)

    print("\nDo you have any other question?")
    print("-" * 50)

